#!/usr/bin/env python3
"""Fetch YouTube video metadata and transcript using yt-dlp.

Usage:
    fetch_transcript.py <video_url> <output_dir> [--lang es,en]

Behavior:
    1. Calls yt-dlp once to get metadata (info.json) + subtitle files.
    2. Prefers manual subtitles over auto-generated.
    3. Picks the first available language from --lang (default: es,en).
    4. Parses the VTT, deduplicating rolling-caption noise.
    5. Writes JSON to stdout with: metadata, chapters, transcript.

The caller (the skill) reads the JSON and renders the final markdown.
Raw artifacts are kept under <output_dir>/.cache/<video_id>/ for inspection.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
YT_DLP = SKILL_DIR / ".venv" / "bin" / "yt-dlp"


def run_yt_dlp(url: str, cache_dir: Path, langs: list[str]) -> Path:
    """Invoke yt-dlp once. Returns the path to the info.json file."""
    cache_dir.mkdir(parents=True, exist_ok=True)
    lang_arg = ",".join(langs)
    cmd = [
        str(YT_DLP),
        "--skip-download",
        "--write-info-json",
        "--write-subs",
        "--write-auto-subs",
        "--sub-langs", lang_arg,
        "--sub-format", "vtt",
        "--no-warnings",
        "-o", str(cache_dir / "%(id)s.%(ext)s"),
        url,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        raise SystemExit(f"yt-dlp failed with code {result.returncode}")
    info_files = list(cache_dir.glob("*.info.json"))
    if not info_files:
        raise SystemExit("yt-dlp produced no info.json")
    return max(info_files, key=lambda p: p.stat().st_mtime)


def pick_subtitle_file(cache_dir: Path, video_id: str, langs: list[str]) -> tuple[Path, str, str] | None:
    """Pick the best available subtitle file.

    Preference: manual over auto, then language order from `langs`.
    Returns (path, lang, kind) or None.
    """
    candidates: list[tuple[int, int, Path, str, str]] = []
    for vtt in cache_dir.glob(f"{video_id}*.vtt"):
        # Filenames look like: <id>.<lang>.vtt for manual, or include lang too for auto.
        # yt-dlp marks auto-generated by writing the file when --write-auto-subs is on,
        # but the filename pattern is the same. We detect by reading the header.
        head = vtt.read_text(encoding="utf-8", errors="ignore")[:200]
        is_auto = "Kind: captions" in head and "auto-generated" in head.lower()
        # Better signal: yt-dlp suffixes auto subs with the lang, manual subs the same.
        # The info.json `automatic_captions` vs `subtitles` is the authoritative source,
        # but for file picking, we infer from the filename order + header.
        lang = vtt.stem.split(".")[-1] if "." in vtt.stem else "unknown"
        try:
            lang_rank = langs.index(lang)
        except ValueError:
            lang_rank = len(langs)
        kind_rank = 1 if is_auto else 0
        candidates.append((kind_rank, lang_rank, vtt, lang, "auto" if is_auto else "manual"))
    if not candidates:
        return None
    candidates.sort(key=lambda c: (c[0], c[1]))
    _, _, path, lang, kind = candidates[0]
    return path, lang, kind


TIMESTAMP_RE = re.compile(r"^(\d{2}):(\d{2}):(\d{2})\.(\d{3})\s+-->\s+(\d{2}):(\d{2}):(\d{2})\.(\d{3})")
INLINE_TAG_RE = re.compile(r"<[^>]+>")


def _parse_ts(h: str, m: str, s: str, ms: str) -> float:
    return int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000


def parse_vtt(vtt_path: Path) -> list[dict]:
    """Parse a YouTube VTT into a list of {start, end, text} cues, deduped.

    YouTube auto-subs emit "rolling" cues where each cue repeats the previous
    cue's text plus a new word. We collapse them by keeping only the longest
    text per overlapping time window, then deduplicate consecutive duplicates.
    """
    raw_cues: list[dict] = []
    lines = vtt_path.read_text(encoding="utf-8", errors="ignore").splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        m = TIMESTAMP_RE.match(line)
        if not m:
            i += 1
            continue
        start = _parse_ts(*m.group(1, 2, 3, 4))
        end = _parse_ts(*m.group(5, 6, 7, 8))
        i += 1
        text_lines = []
        while i < len(lines) and lines[i].strip():
            text_lines.append(lines[i])
            i += 1
        text = " ".join(text_lines)
        text = INLINE_TAG_RE.sub("", text)
        text = re.sub(r"\s+", " ", text).strip()
        if text:
            raw_cues.append({"start": start, "end": end, "text": text})
        i += 1

    # Deduplicate sliding-window cues. YouTube subtitles (both manual and auto)
    # commonly emit each cue as an overlapping window: the suffix of cue N is
    # the prefix of cue N+1. We find the longest suffix/prefix overlap between
    # consecutive cues and keep only the non-overlapping delta.
    incremental: list[dict] = []
    last_text = ""
    for cue in raw_cues:
        text = cue["text"]
        if last_text:
            limit = min(len(last_text), len(text))
            overlap = 0
            for k in range(limit, 0, -1):
                if last_text[-k:] == text[:k]:
                    overlap = k
                    break
            delta = text[overlap:].strip()
        else:
            delta = text
        if delta:
            incremental.append({
                "start": cue["start"],
                "end": cue["end"],
                "text": delta,
            })
        last_text = text
    return incremental


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("url")
    parser.add_argument("output_dir")
    parser.add_argument("--lang", default="es,en", help="Comma-separated language preference order")
    args = parser.parse_args()

    if not YT_DLP.exists():
        raise SystemExit(f"yt-dlp not found at {YT_DLP}. Run scripts/setup.sh first.")

    output_dir = Path(args.output_dir).resolve()
    cache_dir = output_dir / ".cache"
    langs = [l.strip() for l in args.lang.split(",") if l.strip()]

    info_path = run_yt_dlp(args.url, cache_dir, langs)
    info = json.loads(info_path.read_text(encoding="utf-8"))
    video_id = info["id"]

    sub_pick = pick_subtitle_file(cache_dir, video_id, langs)
    transcript: list[dict] = []
    sub_meta = None
    if sub_pick:
        vtt_path, lang, kind = sub_pick
        transcript = parse_vtt(vtt_path)
        sub_meta = {"language": lang, "kind": kind, "source_file": str(vtt_path)}

    payload = {
        "metadata": {
            "id": video_id,
            "title": info.get("title"),
            "uploader": info.get("uploader"),
            "channel": info.get("channel"),
            "channel_url": info.get("channel_url"),
            "upload_date": info.get("upload_date"),
            "duration": info.get("duration"),
            "duration_string": info.get("duration_string"),
            "view_count": info.get("view_count"),
            "webpage_url": info.get("webpage_url"),
            "description": info.get("description"),
            "tags": info.get("tags") or [],
            "categories": info.get("categories") or [],
        },
        "chapters": info.get("chapters") or [],
        "subtitle": sub_meta,
        "transcript": transcript,
        "cache_dir": str(cache_dir),
    }
    json.dump(payload, sys.stdout, ensure_ascii=False)


if __name__ == "__main__":
    main()
